# Generated by Django 2.0.3 on 2018-05-04 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newpols', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='istok',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='news',
            name='ssyl',
        ),
        migrations.RemoveField(
            model_name='news',
            name='zagol',
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
