# Generated by Django 2.0.3 on 2018-05-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpols', '0002_auto_20180504_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=250),
        ),
    ]
