# Generated by Django 2.0.3 on 2018-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlepol', models.CharField(max_length=100)),
                ('linkpol', models.CharField(max_length=250)),
                ('imagepol', models.ImageField(upload_to='img')),
                ('sourcepol', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Politics',
            },
        ),
    ]
