# Generated by Django 2.0.3 on 2018-05-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlesport', models.CharField(max_length=100)),
                ('linksport', models.CharField(max_length=250)),
                ('imagesport', models.ImageField(upload_to='img')),
                ('sourcesport', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sport',
            },
        ),
    ]
